name: Count Lines in Pushed Files

on:
  push:
    branches:
      - master  # Change this to your default branch if different

jobs:
  count_lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Count lines in pushed files
        run: |
          # Loop through each file that was changed in the push
          for file in ${{git diff-tree --no-commit-id --name-only -r ${{ github.sha }} }}; do
            if [ -f "$file" ]; then  # Check if it is a file
              line_count=$(wc -l < "$file")
              echo "File: $file has $line_count lines."
            fi
          done