name: Print Line Count on Push

# Trigger the workflow on every push
on:
  push:
    branches:
      - master   # Trigger on the main branch (change this to any branch you want)

jobs:
  count-lines:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest commit with full history
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all commit history to enable git diff

      # Step 2: Find and print the number of lines in each file pushed
      - name: Count Lines in Pushed Files
        run: |
          # Get a list of changed files in the push (excluding deleted files)
          git diff --name-only HEAD~1 HEAD --diff-filter=d > changed_files.txt
          
          # Loop through the list of files and print their line count
          while read file; do
            if [[ -f $file ]]; then
              line_count=$(wc -l < "$file")
              echo "$file: $line_count lines"
            else
              echo "$file: File does not exist (possibly deleted or moved)"
            fi
          done < changed_files.txt